#! /bin/csh -f
#
# script to create an division index for the embl library in codata format
#

echo "embldivision.script Version 1.0"
echo ""

set RM = "/bin/rm -f"

#
#
#


awk '{printf("%-12.12s %d\n",$1,$2);}' << EOF >! division.list
emseq.all 1
EOF

division division.list division.lkp
if ( $status ) goto abort
${RM} division.list

echo "Completion successful"
echo ""

exit 0

#
# Abort
#
abort:
echo "genbdivision.script: aborting due to serious error"
exit 2
