      SUBROUTINE CONEDT(KBIN,KBOUT,
     +GELNOS,GELSTR,GELEND,
     +MAXDB,GELNO,LINNO,MAXLIN,RELPG,LNGTHG,LNBR,RNBR,
     +IDBSIZ,NGELS,NCONTS,GEL,GEL2,MAXGEL,LINCON,PERCD,IDM,
     +IHELPS,IHELPE,HELPF,IDEVH,IDEV,IDEV1,IDEV2,IDEV3,
     +IDEVT,IDEVC,LINLEN,FILNAM,LLINO,IOK,IERR,TEMP1)
C   AUTHOR: SIMON DEAR
      INTEGER RELPG(MAXDB),LNGTHG(MAXDB),LNBR(MAXDB),RNBR(MAXDB)
      CHARACTER GEL(MAXGEL),GEL2(MAXGEL)
      CHARACTER FILNAM*(*),HELPF*(*)
      INTEGER GELNOS(MAXDB),GELSTR(MAXDB),GELEND(MAXDB)
      INTEGER GELNO(MAXLIN,2),LINNO(MAXLIN,2)
C   DUMMY ROUTINE FOR NON X VERSIONS
      END
      SUBROUTINE JOINED(KBIN,KBOUT,
     +GELNOS,GELSTR,GELEND,
     +MAXDB,GELNO,LINNO,MAXLIN,RELPG,LNGTHG,LNBR,RNBR,
     +IDBSIZ,NGELS,NCONTS,GEL,GEL2,MAXGEL,LINCON,PERCD,IDM,
     +IHELPS,IHELPE,HELPF,IDEVH,IDEV,IDEV1,IDEV2,IDEV3,
     +IDEVT,IDEVC,LINLEN,FILNAM,LLINO,IOK,IERR,TEMP1)
C   AUTHOR: SIMON DEAR
      INTEGER RELPG(MAXDB),LNGTHG(MAXDB),LNBR(MAXDB),RNBR(MAXDB)
      CHARACTER GEL(MAXGEL),GEL2(MAXGEL)
      CHARACTER FILNAM*(*),HELPF*(*)
      INTEGER GELNOS(MAXDB),GELSTR(MAXDB),GELEND(MAXDB)
      INTEGER GELNO(MAXLIN,2),LINNO(MAXLIN,2)
C   DUMMY ROUTINE FOR NON X VERSIONS
      END
      SUBROUTINE JXEDIT(IDEV1,IDEV2,IDEV3,IDEVT,IDEVC,
     +RELPG,LNGTHG,LNBR,RNBR,MAXGEL,
     +IDBSIZ,LR,NR,LL,NL,
     +I,IE,J,IE2,P,NG,NC,IDM,IEXT,IOK)
C   DUMMY ROUTINE FOR NON X VERSIONS
      END
